# Generated by Django 4.2.23 on 2025-06-26 09:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailymetrics',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='dailymetrics',
            name='account',
        ),
        migrations.RemoveField(
            model_name='performancemetrics',
            name='account',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='filled_price',
        ),
        migrations.RemoveField(
            model_name='tradingaccount',
            name='alpaca_api_key',
        ),
        migrations.RemoveField(
            model_name='tradingaccount',
            name='alpaca_secret_key',
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.DeleteModel(
            name='AssetPosition',
        ),
        migrations.DeleteModel(
            name='DailyMetrics',
        ),
        migrations.DeleteModel(
            name='PerformanceMetrics',
        ),
    ]
