# Generated by Django 4.2.23 on 2025-06-27 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_alter_dailymetrics_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradingaccount',
            name='account_id',
        ),
    ]
