# Generated by Django 4.2.23 on 2025-06-27 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_remove_tradingaccount_account_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='profit_loss',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='trade_id',
        ),
    ]
