# Generated by Django 4.2.23 on 2025-06-27 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_accountmetrics_symbolposition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symbolposition',
            name='current_price',
        ),
        migrations.RemoveField(
            model_name='symbolposition',
            name='unrealized_pl',
        ),
    ]
