# Generated by Django 4.2.23 on 2025-06-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_remove_symbolposition_current_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmetrics',
            name='symbols_traded',
            field=models.JSONField(default=list),
        ),
    ]
